// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Semanta Modeler (version 6.5.2.5281)
//      Copyrights © 1995-2019 by COAS Software Systems B.V.
// 
//      Class DbEntityType
//      Entity implementation for object EntityType.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#pragma warning disable 1591

namespace ErrorAnyEF3.DbModel
{

    [Table("EntityType", Schema = "basic")]
    public partial class DbEntityType
    {

        public DbEntityType()
        {
        }

        /// <summary>
        /// Primary key
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        [Column("Id", Order = 1, TypeName = "int")]
        public int Id { get; set; }

        /// <summary>
        /// Description of the EntityType
        /// </summary>
        [Required]
        [Column("Description", Order = 2, TypeName = "nvarchar(80)")]
        [StringLength(80)]
        public string Description { get; set; }

        /// <summary>
        /// Name of the table that is represented by this entity type
        /// </summary>
        [Required]
        [Column("TableName", Order = 3, TypeName = "nvarchar(80)")]
        [StringLength(80)]
        public string TableName { get; set; }

        /// <summary>
        /// If this field is true, the underlying Entity records should 
        /// have a Code field
        /// </summary>
        [Required]
        [Column("HasCode", Order = 4, TypeName = "bit")]
        public bool HasCode { get; set; }

        /// <summary>
        /// A free field to add remarks on the record
        /// </summary>
        [Column("Remarks", Order = 5, TypeName = "nvarchar(500)")]
        [StringLength(500)]
        public string Remarks { get; set; }

        /// <summary>
        /// User who created the record
        /// </summary>
        [Required]
        [Column("CreatedByUserLoginId", Order = 6, TypeName = "int")]
        public int CreatedByUserLoginId { get; set; }

        /// <summary>
        /// User who created the record
        /// </summary>
        [ForeignKey(nameof(CreatedByUserLoginId))]
        public virtual DbUserLogin CreatedByUserLogin { get; set; }

        /// <summary>
        /// Creation data of the record
        /// </summary>
        [Required]
        [Column("CreatedAt", Order = 7, TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// User who last modified the record
        /// </summary>
        [Required]
        [Column("ModifiedByUserLoginId", Order = 8, TypeName = "int")]
        public int ModifiedByUserLoginId { get; set; }

        /// <summary>
        /// User who last modified the record
        /// </summary>
        [ForeignKey(nameof(ModifiedByUserLoginId))]
        public virtual DbUserLogin ModifiedByUserLogin { get; set; }

        /// <summary>
        /// Last modification date of the record
        /// </summary>
        [Required]
        [Column("ModifiedAt", Order = 9, TypeName = "datetime")]
        public DateTime ModifiedAt { get; set; }

        [InverseProperty(nameof(DbEntity.EntityType))]
        public virtual ICollection<DbEntity> Entities { get; set; }

    }

}
